### PR TITLE
#74 Fix infinitely long regex check

### PR DESCRIPTION
**Pull request by benasradzevicius9404**
Fix for infinite loop described in issue #74

### CODE REVIEW

**Comment by gentooboontoo** [comment]
Thanks a lot for your PR. I have made a little change before merging it.

**Comment by tkirda** [comment]
@gentooboontoo could you please release new version to NPM with this change. Thanks!

**Comment by gentooboontoo** [comment]
@tkirda, just released.

**Comment by tkirda** [comment]
Thanks!

**Pull request merged**
